In [2]:
import torch 
from torch import nn

In [18]:
# Tensors 
# pytorch opakowuje wielowymiarowe listy / macierze / tensory w swoją własną wewnętrzną strukturę danych Tensor 
data = [1,2,3,4,5.0]
tensor = torch.tensor(data)

In [19]:
tensor.dtype

torch.float32

In [10]:
len(tensor)

5

In [ ]:
# TODO: utwórzy tensor o wymiarach 2x2 o wartościach 1 [https://pytorch.org/docs/stable/generated/torch.ones.html#torch-ones]
torch.ones(2,2)

In [52]:
# TODO: zapisz go do zmiennej tensor2d 
tensor2d = torch.ones(2,2)

In [53]:
tensor2d.shape 

torch.Size([2, 2])

In [54]:
len(tensor2d)

2

In [55]:
# TODO: Pomnóż nasz tensor2d przez 0.5 

In [56]:
tensor2d * 0.5

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [57]:
# i zapisz wynik do tensor2d

In [58]:
tensor2d = tensor2d * 0.5 

In [59]:
tensor2d

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [75]:
# TODO: Utwórz randomowy tensor 2x2 [https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand]
# TODO: przypisz go do zmiennej rand_tensor2d


In [61]:
rand_tensor2d = torch.rand(2,2)

In [66]:
rand_tensor2d

tensor([[0.2354, 0.1877],
        [0.4091, 0.9473]])

In [64]:
# Pomnóż randomowy tensor z naszym poprzednim "połówkowym" tensorem 
rand_tensor2d * tensor2d

tensor([[0.1177, 0.0939],
        [0.2046, 0.4736]])

In [69]:
class MultiLayerPerceptronA(nn.Module):
    def __init__(self):
        super().__init__()        
        self.sigmoid = nn.Sigmoid()
        self.linear_layer1 = nn.Linear(5, 2)
        self.linear_layer2 = nn.Linear(2, 1)         
        
    def forward(self, x):        
        x = self.linear_layer1(x) # TODO: "przepuść" wejściowy wektor/tensor przez pierwszą warstwę liniową 
        x = self.Sigmoid(x) # TODO: "przepuść" output warstwy liniowej przez sigmoid (aktywuj warstwę) 
        x = self.linear_layer2(x) # TODO: otrzymany wynik przekaż do warstwy drugiej 
        x = self.Sigmoid(x) # TODO: "przepuść" output warstwy liniowej przez sigmoid (aktywuj warstwę) 
        return x

In [70]:
# utwórz instancję MultiLayerPerceptronA i przypisz do zmiennej model 
model = MultiLayerPerceptronA()


In [73]:
# TODO: utwórz randomowy tensor o długości 5 i zaaplikuj na nim metodę forward() 
input = torch.rand(5)
model.forward(input)

tensor([0.5052], grad_fn=<SigmoidBackward0>)

In [74]:
# Alternatywną bardziej elegancką formą definiowania architektury jest użytwanie nn.Sequential 

class MultiLayerPerceptronB(nn.Module):
    def __init__(self):
        super().__init__()        
        self.mlp = nn.Sequential(
            nn.Linear(5, 2),
            nn.Sigmoid(),            
            nn.Linear(2, 1),
            nn.Sigmoid()
        )
        
    def forward(self, x):        
        return self.mlp(x)

In [77]:
# TODO: Utwórz MLP jak w definicji zadania korzystając z nn.Sequential 

class MultiLayerPerceptron(nn.Module):
    def __init__(self):
        super().__init__()        
        self.mlp = nn.Sequential(
            nn.Linear(784, 50),
            nn.Sigmoid(),
            nn.Linear(50,15),
            nn.Sigmoid(),
            nn.Linear(15, 1),
            nn.Sigmoid()
        )
    
    def forward(self, x):        
        return self.mlp(x)


In [78]:
# TODO: stwórz instancję modelu 
model = MultiLayerPerceptron()
# Utwórz randomowy tensor o długości 768 i "przepuść" go przez utworzony model 
input = torch.rand(784)
model.forward(input)

tensor([0.4977], grad_fn=<SigmoidBackward0>)

In [79]:
# Parametry utworzonej sieci 
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name)
        print(param.data)
        print()

mlp.0.weight
tensor([[-0.0259, -0.0346,  0.0117,  ...,  0.0119, -0.0234, -0.0348],
        [-0.0248,  0.0279,  0.0089,  ...,  0.0345, -0.0075,  0.0316],
        [-0.0029, -0.0270, -0.0038,  ..., -0.0353,  0.0343, -0.0315],
        ...,
        [-0.0015, -0.0303, -0.0288,  ...,  0.0209,  0.0322,  0.0183],
        [-0.0035, -0.0126,  0.0276,  ...,  0.0038,  0.0094, -0.0325],
        [ 0.0012, -0.0204,  0.0247,  ...,  0.0259,  0.0177, -0.0122]])

mlp.0.bias
tensor([ 0.0084, -0.0248, -0.0208,  0.0015, -0.0092, -0.0007, -0.0174,  0.0151,
         0.0355, -0.0060,  0.0185, -0.0096,  0.0146,  0.0161, -0.0138, -0.0264,
         0.0318,  0.0249, -0.0324,  0.0008,  0.0090, -0.0049, -0.0306,  0.0356,
         0.0313, -0.0068,  0.0233, -0.0128,  0.0190, -0.0333,  0.0167, -0.0169,
        -0.0354, -0.0148, -0.0142, -0.0026,  0.0308,  0.0144,  0.0025,  0.0072,
        -0.0118, -0.0351,  0.0279, -0.0334,  0.0353,  0.0190, -0.0083,  0.0288,
         0.0171, -0.0357])

mlp.2.weight
tensor([[-4.3014e-02

In [82]:
# Nasz model z wczoraj też może być wyrażony w Pytorch - technicznie to też "bardzo prosta" sieć neuronowa 

class ToyMLModel(nn.Module):
    def __init__(self):
        super().__init__()        
        self.mlp = nn.Sequential(
            nn.Linear(2, 1, bias=False)            
        )
        
    def forward(self, x):        
        return self.mlp(x)

toy = ToyMLModel()
state_dict = toy.state_dict()
state_dict['mlp.0.weight'] = torch.Tensor([[-12500, 24000]])
toy.load_state_dict(state_dict);


In [83]:
toy.forward(torch.Tensor([10, 50]))

tensor([1075000.], grad_fn=<SqueezeBackward4>)